// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// ../../../ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1133

#ifndef ORO_CORBA_CONFIGURATIONINTERFACEI_H_
#define ORO_CORBA_CONFIGURATIONINTERFACEI_H_

#include "corba.h"
#ifdef CORBA_IS_TAO
#include "ConfigurationInterfaceS.h"
#else
#include "ConfigurationInterfaceC.h"
#endif

#include "../../ConfigurationInterface.hpp"
#include "../../PropertyBag.hpp"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  RTT_corba_CConfigurationInterface_i
  : public virtual POA_RTT::corba::CConfigurationInterface
{
     RTT::ConfigurationInterface* mar;
     RTT::PropertyBag* mbag;
     PortableServer::POA_var mpoa;

  public:
    //Constructor
    RTT_corba_CConfigurationInterface_i ( RTT::ConfigurationInterface* ar, PortableServer::POA_ptr the_poa);
    RTT_corba_CConfigurationInterface_i ( RTT::PropertyBag* bag, PortableServer::POA_ptr the_poa );
  // Destructor
  virtual ~RTT_corba_CConfigurationInterface_i (void);

  virtual RTT::corba::CConfigurationInterface_ptr activate_this() {
      PortableServer::ObjectId_var oid = mpoa->activate_object(this); // ref count=2
      //_remove_ref(); // ref count=1
      return _this();
  }

  PortableServer::POA_ptr _default_POA();

  ::RTT::base::DataSourceBase::shared_ptr getAttributeDataSource(const std::string& value_name);
  ::RTT::base::DataSourceBase::shared_ptr getPropertyDataSource(const std::string& value_name);

  virtual
  ::RTT::corba::CConfigurationInterface::CAttributeNames * getAttributeList (
      void);

  virtual
  ::RTT::corba::CConfigurationInterface::CPropertyNames * getPropertyList (
      void);

  virtual
  ::CORBA::Any * getAttribute (
      const char * name);

  virtual
  ::CORBA::Boolean setAttribute (
      const char * name,
      const ::CORBA::Any & value);

  virtual
  ::CORBA::Any * getProperty (
      const char * name);

  virtual
  ::CORBA::Boolean setProperty (
      const char * name,
      const ::CORBA::Any & value);

    CORBA::Boolean hasAttribute(const char* name);
    CORBA::Boolean isAttributeAssignable(const char* name);
  virtual
  char * getAttributeType (
      const char * name);

  virtual
  char * getAttributeTypeName (
      const char * name);

  virtual
  char * attributeToString (
      const char * name);

  virtual
  CORBA::Boolean attributeFromString (
      const char* name, const char* value
    );

    CORBA::Boolean hasProperty(const char* name);
  virtual
  char * getPropertyType (
      const char * name);

  virtual
  char * getPropertyTypeName (
      const char * name);

  virtual
  char * propertyToString (
      const char * name);

  virtual
  CORBA::Boolean propertyFromString (
      const char* name, const char* value
    );
};


#endif /* CONFIGURATIONINTERFACEI_H_  */

