#ifndef ORO_SERVICE_REQUESTER_IDL
#define ORO_SERVICE_REQUESTER_IDL

#ifdef CORBA_IS_TAO
//resolves LNK2005
#include <tao/orb.idl>
#endif

module RTT
{
    module corba
    {

	typedef sequence<string> CRequestNames;
	typedef sequence<string> CMethodNames;

	/**
	 * An Orocos Required Service.
	 * Exposes that this component requires certain services.
	 * @ingroup CompIDL
	 */
	interface CServiceRequester
	{
	    /**
	     * Return the name of this service.
	     */
	    string getRequestName();

	    /**
	     * Get a list of all the child requests this request offers.
	     */
	    CRequestNames getRequestNames( );

	    /**
	     * Returns the methods required by this requester.
	     */
	    CMethodNames getMethodNames();

	    /**
	     * Get a child request this request provides.
	     */
	    CRequestRequester getRequest( in string name );

	    /**
	     * Has this request a child request with given name ?
	     */
	    boolean hasRequest( in string name );

	    boolean connectTo( in CServiceProvider svc);

	    boolean ready();

	    void disconnect();
	};

    };
};
#endif
