#!/bin/sh

# These are all the steps to take if you
# get orocos from Subversion
# (this file is not distributed with the packages)

./autogen.sh
cd packages
./autogen.sh
./configure
make db
cd ..
mkdir build
cd build
../configure --with-gnulinux
make new_packages
make all_packages
