#ifndef ORO_OS_ECOS_H
#define ORO_OS_ECOS_H


#define OROSEM_OS_ECOS_STACK_SIZE 65536

#define OROSEM_OS_SCHEDTYPE CYGSEM_KERNEL_SCHED_MLQUEUE

#define ORONUM_OS_RTOS_HIGHEST_PRIORITY 0

#define ORONUM_OS_RTOS_LOWEST_PRIORITY CYGNUM_KERNEL_SCHED_PRIORITIES-1

#endif
