/**
 * Scripting.cpp
 *
 *  Created on: Feb 1, 2010
 *      Author: kaltan
 */

#include "Scripting.hpp"

namespace RTT
{
    /*
      unloadProgram
      getProgramStatus
      getProgramStatusStr
      getProgramList
      unloadStateMachine
      getStateMachineStatus
      getStateMachineStatusStr
      getStateMachineList
      getStateMachine
      getStateMachine
      execute
      loadPrograms
      loadProgramText
      unloadProgram
      getProgramLine
      getProgramText
      loadStateMachines
      loadStateMachineText
      unloadStateMachine
      getStateMachineText
      getStateMachineLine
      getCurrentState
      startProgram
      stopProgram
      pauseProgram
      stepProgram
      hasProgram
      isProgramRunning
      isProgramPaused
      inProgramError
      activateStateMachine
      deactivateStateMachine
      startStateMachine
      pauseStateMachine
      stopStateMachine
      resetStateMachine
      requestStateMachineState
      hasStateMachine
      isStateMachineActive
      isStateMachineRunning
      inStateMachineError
      isStateMachinePaused
      getStateMachineState
      inStateMachineState
    */
    Scripting::Scripting(TaskContext* owner)
        : ServiceRequester("scripting", owner),
          unloadProgram("unloadProgram"),
          getProgramStatus("getProgramStatus"),
          getProgramStatusStr("getProgramStatusStr"),
          getProgramList("getProgramList"),
          unloadStateMachine("unloadStateMachine"),
          getStateMachineStatus("getStateMachineStatus"),
          getStateMachineStatusStr("getStateMachineStatusStr"),
          getStateMachineList("getStateMachineList"),
          execute("execute"),
          loadPrograms("loadPrograms"),
          loadProgramText("loadProgramText"),
          getProgramLine("getProgramLine"),
          getProgramText("getProgramText"),
          loadStateMachines("loadStateMachines"),
          loadStateMachineText("loadStateMachineText"),
          getStateMachineText("getStateMachineText"),
          getStateMachineLine("getStateMachineLine"),
          getCurrentState("getCurrentState"),
          startProgram("startProgram"),
          stopProgram("stopProgram"),
          pauseProgram("pauseProgram"),
          stepProgram("stepProgram"),
          hasProgram("hasProgram"),
          isProgramRunning("isProgramRunning"),
          isProgramPaused("isProgramPaused"),
          inProgramError("inProgramError"),
          activateStateMachine("activateStateMachine"),
          deactivateStateMachine("deactivateStateMachine"),
          startStateMachine("startStateMachine"),
          pauseStateMachine("pauseStateMachine"),
          stopStateMachine("stopStateMachine"),
          resetStateMachine("resetStateMachine"),
          requestStateMachineState("requestStateMachineState"),
          hasStateMachine("hasStateMachine"),
          isStateMachineActive("isStateMachineActive"),
          isStateMachineRunning("isStateMachineRunning"),
          inStateMachineError("inStateMachineError"),
          isStateMachinePaused("isStateMachinePaused"),
          getStateMachineState("getStateMachineState"),
          inStateMachineState("inStateMachineState")
    {
        addMethod(unloadProgram);
        addMethod(getProgramStatus);
        addMethod(getProgramStatusStr);
        addMethod(getProgramList);
        addMethod(unloadStateMachine);
        addMethod(getStateMachineStatus);
        addMethod(getStateMachineStatusStr);
        addMethod(getStateMachineList);
        addMethod(execute);
        addMethod(loadPrograms);
        addMethod(loadProgramText);
        addMethod(getProgramLine);
        addMethod(getProgramText);
        addMethod(loadStateMachines);
        addMethod(loadStateMachineText);
        addMethod(getStateMachineText);
        addMethod(getStateMachineLine);
        addMethod(getCurrentState);
        addMethod(startProgram);
        addMethod(stopProgram);
        addMethod(pauseProgram);
        addMethod(stepProgram);
        addMethod(hasProgram);
        addMethod(isProgramRunning);
        addMethod(isProgramPaused);
        addMethod(inProgramError);
        addMethod(activateStateMachine);
        addMethod(deactivateStateMachine);
        addMethod(startStateMachine);
        addMethod(pauseStateMachine);
        addMethod(stopStateMachine);
        addMethod(resetStateMachine);
        addMethod(requestStateMachineState);
        addMethod(hasStateMachine);
        addMethod(isStateMachineActive);
        addMethod(isStateMachineRunning);
        addMethod(inStateMachineError);
        addMethod(isStateMachinePaused);
        addMethod(getStateMachineState);
        addMethod(inStateMachineState);
    }

    Scripting::~Scripting()
    {
    }

}
