#ifndef DATASOURCEFACTORYINTERFACE_HPP
#define DATASOURCEFACTORYINTERFACE_HPP

#define  MEMBERFACTORYINTERFACE DataSourceFactoryInterface
#include "MemberFactoryInterface.hpp"
#undef MEMBERFACTORYINTERFACE

#endif
