#ifndef ORO_CORBA_ATTRIBUTES
#define ORO_CORBA_ATTRIBUTES

//resolves LNK2005
#include <tao/orb.idl>
#include "Operations.idl"

module RTT
{
  module Corba
  {
    /**
     * Exposes both attributes and properties
     * of a task as Expression objects.
     * @ingroup CompIDL
     */
    interface AttributeInterface
    {
      struct Property {
	string name;
	string description;
      };

      typedef sequence<Property> PropertyNames;
      typedef sequence<string> AttributeNames;

      AttributeNames getAttributeList();

      PropertyNames  getPropertyList();

      Expression getAttribute( in string name );

      Expression getProperty( in string name );
    };
  };
};


#endif

