#ifndef ORO_CORBA_DATAFLOW_IDL
#define ORO_CORBA_DATAFLOW_IDL

#include "Operations.idl"

module RTT
{
  module Corba
  {
    enum ConnectionModel { Data, Buffer };
    enum LockPolicy { Locked, LockFree };
    struct ConnPolicy
    {
        ConnectionModel type;
        boolean init;
        LockPolicy lock_policy;
        boolean pull;
        long size;
    };

    interface ChannelElement
    {
        void setRemoteSide(in ChannelElement writer);
        boolean read(out any sample);
        oneway void write(in any sample);
        oneway void remoteSignal();
        void remoteDisconnect(in boolean writer_to_reader);
    };

    /** Emitted when information is requested on a port that does not exist */
    exception NoSuchPortException {};
    /** Emitted during connections, when there is no CORBA transport defined
     * for the data type of the given ports
     */
    exception NoCorbaTransport {};

    enum PortType { Input, Output };

    struct PortDescription
    {
        PortType type;
        string   name;
        string   type_name;
    };

    /**
     * An interface to access the dataflow
     * of a ControlTask object. Data ports are exported as
     * assignable expressions (Set/Get). Buffer ports are
     * exported as buffer channels.
     * @ingroup CompIDL
     */
    interface DataFlowInterface
    {
      typedef sequence<string> PortNames;
      typedef sequence<PortDescription> PortDescriptions;

      /**
       * Returns the names of the ports of this component.
       */
      PortNames getPorts();

      /**
       * Returns the names of the ports of this component.
       */
      PortDescriptions getPortDescriptions();

      /**
       * Returns the type of the given port
       */
      PortType getPortType(in string port_name)
            raises(NoSuchPortException);

      /**
       * Returns the data type for the given port
       */
      string getDataType(in string port_name)
            raises(NoSuchPortException);

      /**
       * Check if the given port is already connected to something
       */
      boolean isConnected(in string port_name)
            raises(NoSuchPortException);

      /**
       * Disconnects this port from all connections it is part of
       */
      void disconnect(in string port_name)
            raises(NoSuchPortException);

      /** 
       * Removes the specified connection
       */
      void disconnectPort(in string writer_name,
            in DataFlowInterface reader_iface, in string reader_name);

      /**
       * Creates the reader-half of the connection for the given read port and
       * the given policy
       */
      ChannelElement buildReaderHalf(in string reader_port, in ConnPolicy policy)
            raises(NoCorbaTransport);

      /**
       * Connect the given named port to the given remote port
       *
       * The local port needs to be the reader, while the remote port is the
       * writer
       */
      boolean createConnection(in string local_port, in DataFlowInterface remote_ports,
            in string remote_port, in ConnPolicy policy)
            raises(NoSuchPortException);
    };
  };
};
#endif

