#ifndef ORO_GEOMETRY_IDL
#define ORO_GEOMETRY_IDL

module RTT
{
  module Corba
  {

    typedef sequence<double,3> Vector;
    typedef Vector Position;

    typedef sequence<Vector,3> Rotation;

    struct Frame
    {
      Rotation m;
      Position p;
    };

    struct Twist
    {
      Vector vel;
      Vector rot;
    };

    struct Wrench
    {
      Vector force;
      Vector torque;
    };

    typedef sequence<double> JacCol;

    /**
     * J[row][col] layout.
     */
    typedef sequence<JacCol> Jacobian;
  };
};

#endif
