Document: orocos-rtt
Title: Debian orocos-rtt Manual
Author: <insert document author here>
Abstract: This manual describes what orocos-rtt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orocos-rtt/orocos-rtt.sgml.gz

Format: postscript
Files: /usr/share/doc/orocos-rtt/orocos-rtt.ps.gz

Format: text
Files: /usr/share/doc/orocos-rtt/orocos-rtt.text.gz

Format: HTML
Index: /usr/share/doc/orocos-rtt/html/index.html
Files: /usr/share/doc/orocos-rtt/html/*.html

  
