#ifndef ORO_OROCOS_TYPES_IDL
#define ORO_OROCOS_TYPES_IDL

//resolves LNK2005
#include <tao/orb.idl>

module RTT
{
  module Corba
  {
    // Classical Orocos type
    typedef sequence<double> DoubleSequence;
  };

};


#endif
