/***************************************************************************
  tag: FMTC  Tue Mar 11 21:49:21 CET 2008  ScriptingAccessI.cpp

                        ScriptingAccessI.cpp -  description
                           -------------------
    begin                : Tue March 11 2008
    copyright            : (C) 2008 FMTC
    email                : peter.soetens@fmtc.be

 ***************************************************************************
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU General Public                   *
 *   License as published by the Free Software Foundation;                 *
 *   version 2 of the License.                                             *
 *                                                                         *
 *   As a special exception, you may use this file as part of a free       *
 *   software library without restriction.  Specifically, if other files   *
 *   instantiate templates or use macros or inline functions from this     *
 *   file, or you compile this file and link it with other files to        *
 *   produce an executable, this file does not by itself cause the         *
 *   resulting executable to be covered by the GNU General Public          *
 *   License.  This exception does not however invalidate any other        *
 *   reasons why the executable file might be covered by the GNU General   *
 *   Public License.                                                       *
 *                                                                         *
 *   This library is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *   Lesser General Public License for more details.                       *
 *                                                                         *
 *   You should have received a copy of the GNU General Public             *
 *   License along with this library; if not, write to the Free Software   *
 *   Foundation, Inc., 59 Temple Place,                                    *
 *   Suite 330, Boston, MA  02111-1307  USA                                *
 *                                                                         *
 ***************************************************************************/


// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:910

#include "ScriptingAccessI.h"
#include "OperationsI.h"
#include "../../scripting/ScriptingAccess.hpp"
#include "../../scripting/ProgramLoader.hpp"
#include "../../scripting/parse_exception.hpp"
#include <sstream>

using namespace std;
using namespace RTT;
using namespace RTT::corba;
using namespace RTT::scripting;


// Implementation skeleton constructor
Orocos_CScriptingAccess_i::Orocos_CScriptingAccess_i (RTT::scripting::ScriptingAccess* ee, PortableServer::POA_ptr the_poa)
    :mee(ee), mpoa( PortableServer::POA::_duplicate(the_poa))
{
}

// Implementation skeleton destructor
Orocos_CScriptingAccess_i::~Orocos_CScriptingAccess_i (void)
{
}

PortableServer::POA_ptr Orocos_CScriptingAccess_i::_default_POA()
{
    return PortableServer::POA::_duplicate(mpoa);
}

void Orocos_CScriptingAccess_i::loadPrograms (
    const char * code,
    const char * filename
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException,
    ::RTT::corba::CScriptingAccess::CLoadException
  ))
{
    try {
        mee->loadPrograms( code, filename, true );
    }
    catch (program_load_exception &ple) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( ple.what() );
    } catch(file_parse_exception &fpe) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( fpe.what().c_str() );
    }
}

void Orocos_CScriptingAccess_i::unloadProgram (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException,
    ::RTT::corba::CScriptingAccess::CLoadException
  ))
{
    try {
        mee->unloadProgram( name, true );
    }
    catch (program_unload_exception &ple) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( ple.what() );
    }
}

::RTT::corba::CScriptingAccess::CProgramNames * Orocos_CScriptingAccess_i::getPrograms (

  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    std::vector<std::string> vlist = mee->getPrograms();
    ::RTT::corba::CScriptingAccess::CProgramNames_var result = new ::RTT::corba::CScriptingAccess::CProgramNames();
    result->length( vlist.size() );
    for (unsigned int i=0; i != vlist.size(); ++i )
        result[i] = CORBA::string_dup( vlist[i].c_str() );
    return result._retn();
}

CORBA::Long Orocos_CScriptingAccess_i::getProgramLine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return mee->getProgramLine( name );
}

CORBA::Boolean Orocos_CScriptingAccess_i::hasProgram (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return mee->hasProgram( name );
}

char * Orocos_CScriptingAccess_i::getProgramText (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return CORBA::string_dup( mee->getProgramText(name).c_str() );
}

char * Orocos_CScriptingAccess_i::getProgramStatus (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return CORBA::string_dup( mee->getProgramStatus(name).c_str() );
}

void Orocos_CScriptingAccess_i::loadStateMachines (
    const char * code,
    const char * filename
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException,
    ::RTT::corba::CScriptingAccess::CLoadException
  ))
{
    try {
        mee->loadStateMachines( code, filename, true);
    }
    catch (program_load_exception &ple) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( ple.what() );
    } catch(file_parse_exception &fpe) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( fpe.what().c_str() );
    }
}

void Orocos_CScriptingAccess_i::unloadStateMachine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException,
    ::RTT::corba::CScriptingAccess::CLoadException
  ))
{
    try {
        mee->unloadStateMachine( name, true );
    }
    catch (program_unload_exception &ple) {
        throw ::RTT::corba::CScriptingAccess::CLoadException( ple.what() );
    }
}

::RTT::corba::CScriptingAccess::CStateMachineNames * Orocos_CScriptingAccess_i::getStateMachines (

  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  // Add your implementation here
    std::vector<std::string> vlist = mee->getStateMachines();
    ::RTT::corba::CScriptingAccess::CStateMachineNames_var result = new ::RTT::corba::CScriptingAccess::CStateMachineNames();
    result->length( vlist.size() );
    for (unsigned int i=0; i != vlist.size(); ++i )
        result[i] = CORBA::string_dup( vlist[i].c_str() );
    return result._retn();
}

CORBA::Boolean Orocos_CScriptingAccess_i::hasStateMachine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return mee->hasStateMachine( name );
}

char * Orocos_CScriptingAccess_i::getStateMachineText (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return CORBA::string_dup( mee->getStateMachineText(name).c_str() );
}

char * Orocos_CScriptingAccess_i::getStateMachineStatus (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return CORBA::string_dup( mee->getStateMachineStatus(name).c_str() );
}

CORBA::Long Orocos_CScriptingAccess_i::getStateMachineLine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return mee->getStateMachineLine( name );
}

char * Orocos_CScriptingAccess_i::getCurrentState (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return CORBA::string_dup( mee->getCurrentState(name).c_str() );
}

CORBA::Long Orocos_CScriptingAccess_i::execute (
    const char * code
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
    return mee->execute( code );
}

::RTT::corba::CCommand_ptr Orocos_CScriptingAccess_i::getCommand (
      CORBA::Long ticket
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ))
{
    base::DispatchInterface::shared_ptr ret = mee->getCommand(ticket);
    if ( !ret )
        return corba::CCommand::_nil();
    Orocos_CCommand_i* com = new Orocos_CCommand_i( ret, mpoa.in() );
    return com->_this();

}
