#ifndef ORO_CORBA_SERVICES_IDL
#define ORO_CORBA_SERVICES_IDL

module RTT
{
  module corba
  {

    /**
     * An interface to access the dataflow
     * of a CControlTask object.
     */
    interface CServiceInterface
    {
      /**
       * Retrieve a log message.
       */
      string getLogMessage();

      /**
       * Request the application's ORB to shut down (exit Run()).
       * It will shut down the ORB, it is up to the application
       * if it actually terminates the process as well.
       */
      boolean requestShutdown();

    };
  };
};
#endif
