/***************************************************************************
  tag: Peter Soetens  Tue Dec 21 22:46:15 CET 2004  KernelInterfaceI.h 

                        KernelInterfaceI.h -  description
                           -------------------
    begin                : Tue December 21 2004
    copyright            : (C) 2004 Peter Soetens
    email                : peter.soetens@mech.kuleuven.ac.be
 
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 
 
// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:969

#ifndef KERNELINTERFACEI_H_
#define KERNELINTERFACEI_H_

#include "kernelinterface.hpp"
#include "KernelInterfaceS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ih.cpp:57

namespace ExecutionClient {
    class DirectKernelInterface;
}

class  Orocos_KernelInterface_i : public virtual POA_Orocos::KernelInterface
{
    ExecutionClient::KernelInterface* _dki;
public:
  //Constructor 
  Orocos_KernelInterface_i ( ExecutionClient::KernelInterface* dki );
  
  //Destructor 
  virtual ~Orocos_KernelInterface_i (void);
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean requestShutdown (
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

  
  virtual ::Orocos::KernelInterface::NameList * getProgramNames (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getStateMachineNames (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void loadStateMachines (
    const char * code,
    const char * filename
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Orocos::LoadException
    , Orocos::ParseException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean unloadStateMachine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Orocos::LoadException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void loadPrograms (
    const char * code,
    const char * filename
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Orocos::LoadException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean unloadProgram (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Orocos::LoadException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getLogLine (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getProgramText (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getStateText (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getProgramStatus (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Long getProgramLine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getStateStatus (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Long getStateLine (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getState (
    const char * name
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getControllers (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getGenerators (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getEffectors (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getEstimators (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getSensors (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getSupports (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getComponents (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getCommands (
    const char * comp
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getData (
    const char * comp
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Orocos::KernelInterface::NameList * getMethods (
    const char * comp
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Long startExecutingCommand (
    const char * code
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Orocos::LoadException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean isCommandFinished (
    CORBA::Long commandid
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void abandonCommand (
    CORBA::Long commandid
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));
};


#endif /* KERNELINTERFACEI_H_  */
