/***************************************************************************
  tag: Peter Soetens  Mon Jun 26 13:25:59 CEST 2006  FactoriesI.h 

                        FactoriesI.h -  description
                           -------------------
    begin                : Mon June 26 2006
    copyright            : (C) 2006 Peter Soetens
    email                : peter.soetens@fmtc.be
 
 ***************************************************************************
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Lesser General Public            *
 *   License as published by the Free Software Foundation; either          *
 *   version 2.1 of the License, or (at your option) any later version.    *
 *                                                                         *
 *   This library is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *   Lesser General Public License for more details.                       *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with this library; if not, write to the Free Software   *
 *   Foundation, Inc., 59 Temple Place,                                    *
 *   Suite 330, Boston, MA  02111-1307  USA                                *
 *                                                                         *
 ***************************************************************************/
 
 
// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:844

#ifndef FACTORIESI_H_
#define FACTORIESI_H_

#include "FactoriesS.h"
#include "../OperationInterface.hpp"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  Orocos_MethodInterface_i : public virtual POA_Orocos::MethodInterface, public virtual PortableServer::RefCountServantBase
{
    RTT::MethodFactory* mfact;
public:
  //Constructor 
  Orocos_MethodInterface_i (RTT::MethodFactory* mfact);
  
  //Destructor 
  virtual ~Orocos_MethodInterface_i (void);
  
  virtual
  ::Orocos::MethodList * getMethods (
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  virtual
  ::Orocos::Descriptions * getArguments (
      const char* method
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
      ,Orocos::NoSuchNameException
    ));
  
  virtual
  char * getResultType (
      const char* method
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
      ,Orocos::NoSuchNameException
    ));
  
  virtual
  char * getDescription (
      const char* method
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
      ,Orocos::NoSuchNameException
    ));
  
  virtual
  ::Orocos::Method_ptr createMethod (
      const char * method,
      const ::Orocos::Arguments& args
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ,Orocos::WrongNumbArgException
    ,Orocos::WrongTypeArgException
    ));

  virtual
  ::Orocos::Method_ptr createMethodAny (
      const char * method,
      const ::Orocos::AnyArguments& args
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ,Orocos::WrongNumbArgException
    ,Orocos::WrongTypeArgException
    ));
};

class  Orocos_CommandInterface_i : public virtual POA_Orocos::CommandInterface, public virtual PortableServer::RefCountServantBase
{
    RTT::CommandFactory* mfact;
public:
  //Constructor 
  Orocos_CommandInterface_i (RTT::CommandFactory* fact);
  
  //Destructor 
  virtual ~Orocos_CommandInterface_i (void);
  
  virtual
  ::Orocos::CommandList * getCommands (
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));

  virtual
  ::Orocos::Descriptions * getArguments (
      const char* command
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ));
  
  virtual
  char * getResultType (
      const char* command
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ));
  
  virtual
  char * getDescription (
      const char* command
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ));
  
  virtual
  ::Orocos::Command_ptr createCommand (
      const char * command,
      const ::Orocos::Arguments& args
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ,Orocos::WrongNumbArgException
    ,Orocos::WrongTypeArgException
    ));
  
  virtual
  ::Orocos::Command_ptr createCommandAny (
      const char * command,
      const ::Orocos::AnyArguments& args
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ,Orocos::NoSuchNameException
    ,Orocos::WrongNumbArgException
    ,Orocos::WrongTypeArgException
    ));
};


#endif /* FACTORIESI_H_  */

