#ifndef RTT_CONFIG_H
#define RTT_CONFIG_H
/*
 * File <rtt/rtt-config.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define OROPKG_OS_LXRT
#define OROPKG_SUPPORT
#define OROPKG_SUPPORT_RTAI
#define OROPKG_SUPPORT_BOOST
#define OROPKG_SUPPORT_CORBA
#define OROPKG_SUPPORT_GCC
#define OROPKG_SUPPORT_XERCESC
#define OROPKG_CORELIB
#define OROPKG_OS
#define OROPKG_CORELIB_EVENTS
#define OROPKG_CORELIB_BUFFERS
#define OROPKG_CORELIB_ACTIVITIES
#define OROPKG_CORELIB_COMMANDS
#define OROPKG_CORELIB_CONDITIONS
#define OROPKG_CORELIB_PROPERTIES
#define OROPKG_CORELIB_PROPERTIES_MARSHALLING
#define OROPKG_CORELIB_REPORTING
#define OROPKG_CORELIB_TIMING
#define OROPKG_DEVICE_INTERFACE
#define OROPKG_DEVICE_INTERFACE_ENCODER
#define OROPKG_DEVICE_INTERFACE_LOGICAL
#define OROPKG_DEVICE_INTERFACE_IO
#define OROPKG_EXECUTION
#define OROPKG_EXECUTION_PROGRAM_PARSER
#define OROPKG_EXECUTION_PROGRAM_PROCESSOR
#define OROPKG_EXECUTION_TASK_CONTEXT

#endif
