
#ifndef OROCOS_SIGNAL_SIGNAL0_HEADER
#define OROCOS_SIGNAL_SIGNAL0_HEADER

#define OROCOS_SIGNAL_NUM_ARGS 0
#define OROCOS_SIGNAL_TEMPLATE_PARMS
#define OROCOS_SIGNAL_TEMPLATE_ARGS
#define OROCOS_SIGNAL_PARMS
#define OROCOS_SIGNAL_ARGS
#define OROCOS_SIGNAL_ARG_TYPES
#define OROCOS_SIGNAL_CONNECTION_TYPEDEFS

#include "signal_template.hpp"

#undef OROCOS_SIGNAL_CONNECTION_TYPEDEFS
#undef OROCOS_SIGNAL_ARG_TYPES
#undef OROCOS_SIGNAL_ARGS
#undef OROCOS_SIGNAL_PARMS
#undef OROCOS_SIGNAL_TEMPLATE_ARGS
#undef OROCOS_SIGNAL_TEMPLATE_PARMS
#undef OROCOS_SIGNAL_NUM_ARGS

#endif // OROCOS_SIGNAL_SIGNAL0_HEADER
